### ISSUE TITLE
Create a coach

### ISSUE THREAD

**Issue by joshimhoff** [northern-bites/nbites#609]
New rules allow for a "coach" robot to watch the game from off field and communicate (with limited bandwidth) with his team.

He could...
- Correct flipped robots (along with "dangerous ball")
- Perform calloffs based on who is closest (vision-based calloffs)
- Communicate the ball's position when no one else sees it
- Somehow be useful as a strategist -- perhaps role-switching is done by the coach?

Lots of potential here but also lots of work!

**Comment by kmushegi** [comment]
Maybe we could create a tag like "possible project" and mark things like this as such because this could potentially be useful in the future, or someone might want to do something with this. Good to keep things on the radar, without them being lost in multiple iterations of Google Docs projects from year to year.
